config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'

  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'

  get 'tasks/:id', to: 'tasks#show', as: 'task'

  post 'tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_tasks'

  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'

  patch 'tasks/:id', to: 'tasks#complete', as: 'complete_task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy complete]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path
  end

  def edit; end

  def update
    @task.update(task_params)

    redirect_to tasks_path
  end

  def destroy
    @task.destroy

    redirect_to tasks_path, status: :see_other
  end

  def complete
    @task.update(completed: true)
    redirect_to task_path(@task)
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-4 mt-4">
      <%= form_with model: @task do |f| %>
        <div class="form-group">
          <%= f.label :title, class: "custom-label" %>
          <%= f.text_field :title, class: "custom-input form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :details, class: "custom-label" %>
          <%= f.text_field :details, class: "custom-input form-control" %>
        </div>
        <div class="d-flex justify-content-between align-items-end mt-3">
          <%= link_to "Back", task_path, class: "btn btn-secondary btn-sm" %>
          <%= f.submit "Save", class: "custom-button btn btn-primary btn-sm" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
  <%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My Tasks</h1>
  <div class="row">
    <ul class="list-group">
      <% @tasks.each do |task| %>
        <li class="list-group-item col-md-4">
          <% if task.completed %>
            <i class="fas fa-check-square"></i>
          <% else %>
            <i class="far fa-square"></i>
          <% end %>
          <%= link_to task.title, task_path(task), class: "task-link" %>
        </li>
      <% end %>
    </ul>
  </div>
  <%= link_to 'Create new task', '/tasks/new', class: "btn btn-primary btn-sm mt-2" %>
</div>

app/views/tasks/new.html.erb
<div class="container">
<%= render "form", task: @task %>
<%= link_to "Back to list", "/tasks", :class => "btn btn-secondary btn-sm" %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1>Task Details</h1>
  <div>
    <h2><%= @task.title %></h2>
    <p><%= @task.details %></p>
    <%= link_to "Mark as Complete", complete_task_path(@task), method: :patch  %>
  </div>
    <%= link_to "Back to list", tasks_path, :class => "btn btn-secondary btn-sm"%>
    <%= link_to "Update task", edit_tasks_path, :class => "btn btn-primary btn-sm" %>
    <%= link_to "Delete",
    task_path(@task),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, :class => "btn btn-danger btn-sm"%>
</div>